apiVersion: v1
kind: Service
metadata:
   name: billing-api-service
   labels:
    app: billing-service
spec:
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: billing-service
  type: LoadBalancer

  